const mongoose = require('mongoose');
const { Question, QuestionPaper } = require('../models');
const { organizationIdForWrite, organizationScope } = require('../services/organizationService');
const { paperInputFromBody, questionPaperSummary } = require('../services/questionPaperService');
const {
  PaperGenerationError,
  generationQuery,
  parseGenerationRules,
  replacementCriteria,
  selectQuestionsForBlueprint,
} = require('../services/paperGeneratorService');
const { _private:paperHelpers } = require('./questionPaperController');

const COURSES = ['JEE','CET','NEET'];
const SUBJECTS = ['Physics','Chemistry','Mathematics','Biology','English','General Knowledge'];
const QUESTION_TYPES = ['SINGLE_CORRECT','MULTIPLE_CORRECT','NUMERICAL','TRUE_FALSE'];

function responseError(res, error) {
  if (error instanceof PaperGenerationError) {
    return res.status(422).json({ error:error.message, code:error.code, details:error.details });
  }
  console.error('Auto paper error:', error);
  return res.status(500).json({ error:'Unable to generate the question paper.' });
}

function serializeSelection(questions) {
  return questions.map(paperHelpers.serializeQuestion);
}

exports.getGenerator = async (req, res) => {
  try {
    const [topics, tags] = await Promise.all([
      Question.distinct('topic', { isActive:true, ...organizationScope(req.organization) }),
      Question.distinct('tags', { isActive:true, ...organizationScope(req.organization) }),
    ]);
    res.render('admin/auto-paper-generator', {
      title:'Auto Generate Question Paper', COURSES, SUBJECTS, QUESTION_TYPES,
      topics:topics.filter(Boolean).sort(), tags:tags.filter(Boolean).sort(),
    });
  } catch (error) { console.error(error); req.flash('error','Unable to open the paper generator.'); res.redirect('/admin/question-papers'); }
};

exports.preview = async (req, res) => {
  try {
    const rules = parseGenerationRules(req.body.rules || req.body);
    const candidates = await Question.find(generationQuery(rules, organizationScope(req.organization)));
    const selected = selectQuestionsForBlueprint(candidates, rules);
    return res.json({ rules, questions:serializeSelection(selected), summary:questionPaperSummary(selected), inventory:candidates.length });
  } catch (error) { return responseError(res, error); }
};

exports.replace = async (req, res) => {
  try {
    const rules = parseGenerationRules(req.body.rules || req.body);
    const submittedSelectedIds = Array.isArray(req.body.selectedQuestionIds)
      ? req.body.selectedQuestionIds
      : req.body.selectedQuestionIds ? [req.body.selectedQuestionIds] : [];
    const selectedIds = [...new Set(submittedSelectedIds.map(String))];
    const replaceId = String(req.body.replaceQuestionId || '');
    if (!mongoose.isValidObjectId(replaceId) || selectedIds.some(id => !mongoose.isValidObjectId(id))) {
      throw new PaperGenerationError('Replacement request contains an invalid question ID.');
    }
    const current = await Question.findOne({ _id:replaceId, ...organizationScope(req.organization) });
    if (!current) throw new PaperGenerationError('The question to replace is unavailable.');
    const baseQuery = generationQuery(rules, organizationScope(req.organization));
    const criteria = replacementCriteria(current, rules, true);
    const replacements = await Question.find({
      $and:[baseQuery, criteria, { _id:{ $nin:selectedIds } }],
    }).limit(100);
    if (!replacements.length) {
      throw new PaperGenerationError(
        `No unused ${current.difficulty} question with ${current.marks} mark(s) matches these rules.`,
        'NO_REPLACEMENT',
        { difficulty:current.difficulty, marks:current.marks }
      );
    }
    const replacement = replacements[Math.floor(Math.random() * replacements.length)];
    return res.json({ question:paperHelpers.serializeQuestion(replacement) });
  } catch (error) { return responseError(res, error); }
};

exports.save = async (req, res) => {
  try {
    const rules = parseGenerationRules(req.body);
    const ids = paperHelpers.selectedIds(req.body);
    const questions = await paperHelpers.questionsForIds(req, ids);
    const input = paperInputFromBody(req.body, questions);
    input.code = await paperHelpers.availableCode(req, input.code, input.title);
    const finalSummary = questionPaperSummary(questions);
    const requestedDistribution = rules.difficultyCounts;
    const matchesBlueprint = finalSummary.totalQuestions === rules.totalQuestions
      && finalSummary.totalMarks === rules.totalMarks
      && ['Easy','Medium','Hard'].every(level => finalSummary.difficultyDistribution[level] === requestedDistribution[level]);
    const paper = await QuestionPaper.create({
      ...input,
      organization:organizationIdForWrite(req),
      createdBy:req.session.user.id,
      autoGenerated:true,
      generationRules:{ ...rules, matchesFinalSelection:matchesBlueprint },
      isActive:true,
    });
    req.flash('success', matchesBlueprint
      ? 'Generated question paper saved.'
      : 'Adjusted question paper saved. Its final distribution differs from the original blueprint.');
    return res.redirect(`/admin/question-papers/${paper._id}`);
  } catch (error) {
    console.error('Save generated paper error:', error);
    req.flash('error', `Unable to save generated paper: ${error.message}`);
    return res.redirect('/admin/question-papers/generate');
  }
};

exports._private = { serializeSelection };
