const mongoose = require('mongoose');

const questionPaperSchema = new mongoose.Schema({
  organization: { type:mongoose.Schema.Types.ObjectId, ref:'Organization', default:null, index:true },
  title: { type:String, required:true, trim:true, maxlength:200 },
  code: { type:String, required:true, trim:true, uppercase:true, maxlength:60, match:/^[A-Z0-9_-]+$/ },
  description: { type:String, default:null, trim:true, maxlength:2000 },
  course: { type:String, default:null, trim:true, uppercase:true, index:true },
  subjects: { type:[String], default:[] },
  topics: { type:[String], default:[] },
  subtopics: { type:[String], default:[] },
  tags: { type:[String], default:[], index:true },
  questionIds: [{ type:mongoose.Schema.Types.ObjectId, ref:'Question' }],
  totalQuestions: { type:Number, min:0, default:0 },
  totalMarks: { type:Number, min:0, default:0 },
  difficultyDistribution: {
    Easy:{ type:Number, min:0, default:0 },
    Medium:{ type:Number, min:0, default:0 },
    Hard:{ type:Number, min:0, default:0 },
  },
  questionTypeDistribution: { type:mongoose.Schema.Types.Mixed, default:{} },
  createdBy: { type:mongoose.Schema.Types.ObjectId, ref:'User', required:true },
  status: { type:String, enum:['draft','ready','archived'], default:'draft', index:true },
  autoGenerated: { type:Boolean, default:false },
  generationRules: { type:mongoose.Schema.Types.Mixed, default:null },
  duplicatedFrom: { type:mongoose.Schema.Types.ObjectId, ref:'QuestionPaper', default:null },
  isActive: { type:Boolean, default:true, index:true },
}, { timestamps:true });

function uniqueStrings(values, { uppercase = false } = {}) {
  return [...new Set((values || []).map(value => String(value).trim()).filter(Boolean)
    .map(value => uppercase ? value.toUpperCase() : value))];
}

questionPaperSchema.pre('validate', function normalizeQuestionPaper() {
  this.tags = uniqueStrings(this.tags);
  this.subjects = uniqueStrings(this.subjects);
  this.topics = uniqueStrings(this.topics);
  this.subtopics = uniqueStrings(this.subtopics);
  this.questionIds = [...new Map((this.questionIds || []).map(id => [String(id), id])).values()];
  this.totalQuestions = this.questionIds.length;
});

questionPaperSchema.index(
  { organization:1, code:1 },
  { unique:true, partialFilterExpression:{ isActive:true } }
);
questionPaperSchema.index({ organization:1, status:1, createdAt:-1 });
questionPaperSchema.index({ organization:1, course:1, subjects:1, tags:1 });

module.exports = mongoose.models.QuestionPaper || mongoose.model('QuestionPaper', questionPaperSchema);
